### ISSUE TITLE
vm: * The host path of the shared folder is missing: vHosts/

### ISSUE THREAD

**Issue by vdespa** [perltwiesekt/vagrant-typo3cms#1]
Following the instructions, after `vagrant up` the following error shows up:

    vm:
    * The host path of the shared folder is missing: vHosts/

Fixed by creating the required folders:

    mkdir -p vHosts/t3-cms/Web

Thanks for sharing. Just wanted to let you know about this.

**Comment by perltwiesekt** [comment]
Thanks for the tip, fixed in README.
